config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :doctors

   root 'doctors#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    has_many :patients
    validates_uniqueness_of :license_number
    validates_uniqueness_of :phone_number
    validates_uniqueness_of :email
    validates_format_of :phone_number, with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/
    validates_format_of :email, :with => /\A([^@\s]+)@((gmail)\.+com)\Z/i, :on => :create ,:message =>"must be @gmail.com"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :doctor
validates_presence_of :first_name, message: 'please fill the blank'
validates_presence_of :last_name, message: 'please fill the blank'
validates_uniqueness_of :first_name
validates_uniqueness_of :last_name
validates_uniqueness_of :phone
validates_format_of :phone, with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/
validates_uniqueness_of :email
validates_format_of :email, :with => /\A([^@\s]+)@((gmail)\.+com)\Z/i, :on => :create ,:message =>"must be @gmail.com"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :license_number, :email, :phone_number)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :phone, :status, :doctor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :license_number %><br>
    <%= f.text_field :license_number, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, class:"form-control" %>
  </div>
 
  <div class="actions">
    <%= f.submit 'save', class:"btn btn-info" %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table class="table table-bordered">
  <thead>
    <tr  class="success">
      <th>First name</th>
      <th>Last name</th>
      <th>License number</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.license_number %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.phone_number %></td>
        <td><%= link_to 'Show', doctor, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path, class:"btn btn-success" %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Doctor:<%= @doctor.first_name %></h2>
<table class='table-striped table table-bordered table-hover'>
  <thead>
 <tr  class="success">
      <th><center>First name</center></th>
      <th><center>Last name</center></th>
      <th><center>License number</center></th>
      <th><center>Email</center></th>
      <th><center>Phone Number</center></th>
    </tr>
  </thead>
   <tbody>
    
      <tr>
        <td><center><%= @doctor.first_name %></center></td>
        <td><center><%= @doctor.last_name %></center></td>
         <td><center><%= @doctor.license_number %></center></td>
        <td><center><%= @doctor.email %></center></td>
        <td><center><%= @doctor.phone_number %></center></td>
      </tr>
  </tbody>
</table>
<hr>

 <h2>Patients List:</h2><br>
 <% @doctor.patients.each do |g| %>

<table class='table-striped table table-bordered table-hover'>
  <thead>
 <tr  class="danger">
      <th><center>First name</center></th>
      <th><center>Last name</center></th>
      <th><center>Email</center></th>
      <th><center>Phone</center></th>
     
    </tr>
  </thead>
   <tbody>
    
      <tr>
        <td><center><%= g.first_name %></center></td>
        <td><center><%= g.last_name %></center></td>
         <td><center><%= g.email %></center></td>
        <td><center><%= g.phone %></center></td>
       
      </tr>
  </tbody>
</table>
 <%end%>

<hr>
<%= link_to 'Edit', edit_doctor_path(@doctor), class:"btn btn-warning" %> |
<%= link_to 'Back', doctors_path, class:"btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
<%= yield %>
</div>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="table table-bordered">
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  
  </table>
  <span>Doctors:</span>
 <%= f.collection_select :doctor_id, Doctor.order(:first_name), :id, :first_name %>
 <br>
 <br>
 
 
  <div class="actions">
    <%= f.submit 'save', class:"btn btn-info" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table class="table table-bordered">
  <thead>
    <tr class="success">
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Status</th>
     
      <th colspan="3"><center>Actions</center></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.status %></td>
       
        <td><%= link_to 'Show', patient, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class:"btn btn-success" %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<table class='table-striped table table-bordered table-hover'>
  <thead>
 <tr  class="success">
      <th><center>First name</center></th>
      <th><center>Last name</center></th>
      <th><center>Email</center></th>
      <th><center>Phone</center></th>
      <th><center>Status</center></th>
      <th><center>Seen by Doctor</center></th>
      <th><center>Doctor's email address</center></th>
      <th><center>Doctor's phone No.</center></th>
     
    </tr>
  </thead>
   <tbody>
    
      <tr>
        <td><center><%= @patient.first_name %></center></td>
        <td><center><%= @patient.last_name %></center></td>
        <td><center><%= @patient.email %></center></td>
        <td><center><%= @patient.phone %></center></td>
        <td><center><%= @patient.status %></center></td>
        <td><center><%= @patient.doctor.first_name %></center></td>
        <td><center><%= @patient.doctor.email %></td>
        <td><center><%= @patient.doctor.phone_number %></td>
      </tr>
  </tbody>
</table>




<%= link_to 'Edit', edit_patient_path(@patient), class:"btn btn-warning" %> |
<%= link_to 'Back', patients_path, class:"btn btn-warning" %>